language: node_js
node_js:
- '6'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "WTboLu0+qOFuqT538pnn7tvwMu258hBvkHi5pyghVO1MC5s4eb6C7qLTEyRvcu0ExYJ7ijK7Cy4Dd4UwPSXyhY2egh+2kyL+BrKd0C/LngweBhqiG6Fb7/fdhbskLsxJFlnLtWezaGJWP4uQTk/QmfaO8udKFMaxe3girXR0hHwpaoWj32dxKZ7nCaSIT4+Oa7whR28ZES3WKgsLV8DS1UCCIUxZ1+K1tOhay+aLQzSMlgKocyEfOKECQfs+9QakBxn95oRSC7+miN6WtwV5QtDA1XtgdtG2NUSFAwPQpRyteuYfQiVio0rZlATG0j3xguu67MG3OUQ0pWPUMf0fPq5c7quxuGO8Le272XWmOxyRwKHi90ZsalHcg6WKIFpwdoWNRoDqYDhgs7K1SGVv4whbcxmW7BWFp1wWiW+Dji68TjEAFrY3RlqdGDNbUoUgyhB3BBVFzHAyfLvskEc03G+mqJC05gjn1vStVK2JwhyPat085tS5i+pykxunNp26AYywiaiKgubCF6J56/4ia7GcaQvHMNxMIZ/N11GbSB/np3PzgzxbMYHRIvNo+vjnZ1r1XNvEuckhTu7M6HJQ0p4fM74Sxl8cj11KPAmGcoQrMbTlqo3u+++cUioENwuKiXlsf7zgyFImYQrub7tsJJX2xMPsnxfikw7Ya7ucWr8="
env:
  secure: "tw9UOXwbf3sCNlU7lDeGlKWxTy/lcV4iZxwVO18oVZFtLcHHSnHW4ub8qohBjNfG/MrkH8shFS9qjTY4NlYyIOpWhsGfKPkk01w2HasjDxhJece1OVY8hkv/xisHPzvYJ/KsRk3KVusSiUfQoniIEZwlgSIFc3cPs4PG/4ustnbBesaHABVWSsKujtQt3sKsa0g+UUmRyAW4vbfY6kT+1EXmx6fREiZQJGljshxs3x6mIx+/ybv1Ue2FZ8RdyN5pyhOGQilWWmUABA1ZP46X/xL9liCaD3ht/hje/DKqrjCcyu1q8Z30/jsNka1/GoMCKY5KQh+0w3+9HCfB+JY2PM3aLQrB66e42wVEkRHLyBn1e7hCsLdXuFWsK4sDf9hvYQy7fYFCnw4v/hcVpk77vtoeZeGuF9nBHNyH4mBaJv8gf+mhRUfiQDVFQ1dvplCwj4hNkkgXJOZCFaYF5lOlldRSzPA0befa8TghNGr/Out3nbmg+61FF4/HNhqQzxlJ/x9RwqKBPY7bTn9FtgIHPPZzz2FAslrRCfhq/I8FplEXkz2OZqN9N6FJ/MHCcDTxbsmzNCAIaT99CnjecYWIPmWcDfBPMQPOILHYqmRRAVgXnJlJ3L+eQ6fkyGxLD5UJBteXmDRG+Pj7xqJ9Sa7g9flJQW5yvRPc6M3+S7vFNoo="
